class Api::V1::RecipesController < ApplicationController
  # require 'rest-client'
  include CurrentUserConcern

  def index
    @recipes = Recipe.all
    @recipe = Recipe.new
  end

  def create
    @current_user = User.find_by(id: session[:id]) if session[:id]
    @recipe = Recipe.new(recipes_params)
    @recipe = Recipe.scraper(@recipe)
    @recipe.user = @current_user
    @recipe.save
    @instructions = Instruction.parse(@recipe.steps)
    @instructions.shift
    @instructions.each do |instruction|
      instruction.gsub!(/\A\s\d*\s*/, "")
      Instruction.create(content: instruction, recipe: @recipe)
    end
    # @ingredients = Ingredient.parse(@recipe.ingredients)
    # @ingredients.each do |ingredient|
    #   Ingredient.create(content: ingredient, recipe: @recipe)
    # end
    create_playlist(@recipe)

    render json: {
      id: @recipe.id,
      playlistId: @recipe.playlist["spotify_playlist_id"]
    }
  end

  def typed_recipe
    @current_user = User.find_by(id: session[:id]) if session[:id]
    @recipe = Recipe.new(recipe_params)
    @recipe.user = @current_user
    # @recipe.ingredients = recipes_params[:ingredients]
    @recipe.save
    @instructions = recipes_params[:instructionsString].split('-')
    @instructions.shift
    @instructions.each do |instruction|
      Instruction.create(content: instruction, recipe: @recipe)
    end
    create_playlist(@recipe)

    render json: {
      id: @recipe.id,
      playlistId: @recipe.playlist["spotify_playlist_id"]
    }
  end

  def show
    @recipe = Recipe.find(params[:id])
    render json: {
      recipe: @recipe,
      playlist: @recipe.playlist["spotify_playlist_id"]
    } # * send the recipe data sa json to the frontend
  end

  # def update
  #   @recipe = Recipe.find(params[:id])
  #   @recipe.update(favorite: true)
  #   redirect_to recipe_path(@recipe)
  # end

  # def destroy
  #   @recipes.destroy
  #   redirect_to recipes_path
  # end

  private

  def create_playlist(recipe)
    recipe.playlist = Playlist.create({
                                        spotify_playlist_id: create_spotify_playlist(@recipe.preptime.to_i, @recipe.title),
                                        recipe_id: @recipe.id
                                      })
  end

  # * the #create_spotify_playlist takes two paraments the spotify user and the prep_time from the scrapper
  # * the #create_spotify_playlist generates and populates the user recipe

  def create_spotify_playlist(prep_time, playlist_name)
    hdrs = return_header
    # * currate the songs array, it must hold either tracks or a collection of strings that is a valid spotify track uri
    songs = curate_playlist(prep_time)
    # * CREATE THE PLAYLIST
    payload = {
      name: "Jammaker #{playlist_name}",
      description: "An automated playlist generated by jammaker.lol so that you dont ever have to fiddle with your music again",
      public: false
    }
    playlist = JSON.parse(RestClient.post("https://api.spotify.com/v1/users/#{@current_user.spotify_id}/playlists", payload.to_json, hdrs))
    send_playlist(playlist, songs)
  end

  def fetch_genre_url
    # * get the categories
    "https://api.spotify.com/v1/browse/categories/#{recipes_params[:genre]}"
  end

  def fetch_playlist_response
    hdrs = return_header
    # * get the playlist url from the category
    playlist_response = fetch_genre_url
    if RestClient::Request.new({
                                 url: "#{playlist_response}/playlists",
                                 method: "GET",
                                 headers: hdrs
                               }).execute.code == 404
      playlist_response = fetch_genre_url
    end
    JSON.parse(RestClient.get("#{playlist_response}/playlists", hdrs))
  end

  def fetch_song
    hdrs = return_header
    playlist_response = fetch_playlist_response
    playlist_url = playlist_response['playlists']['items'][rand(playlist_response.length) - 1]['href']
    # * get the song url from the playlist
    total_songs = JSON.parse(RestClient.get("#{playlist_url}/tracks?", hdrs))
    song_response = JSON.parse(RestClient.get("#{playlist_url}/tracks?&limit=1&offset=#{rand(total_songs['total'])}", hdrs))
    [song_response['items'].first['track']['uri'], song_response['items'].first['track']['duration_ms']] # * <---- return song
  end

  def recipes_params
    params.require(:recipeData).permit(:url,
                                       :genre,
                                       :ingredients,
                                       :instructionsString,
                                       :preptime,
                                       :title)
  end

  def curate_playlist(prep_time)
    # * currate the songs array, it must hold either tracks or a collection of strings that is a valid spotify track uri
    songs = []
    # TODO: calculate the total duration of all the songs inside the songs array
    playlist_time = 0
    # * looping until the total playlist time reaches the total preptime
    until playlist_time >= prep_time
      song = fetch_song
      puts "playlist time: #{playlist_time} prep time: #{prep_time}"

      next if songs.include?(song[0])

      songs.push(song[0])
      playlist_time += song[1] / 60_000
    end
    songs
  end

  def send_playlist(playlist, songs)
    hdrs = return_header
    RestClient.post("https://api.spotify.com/v1/playlists/#{playlist['id']}/tracks?uris=#{songs.join(',')}", {}, hdrs)
    playlist["id"]
  end

  def return_header
    enc_credentials = "Bearer #{@current_user.access_token}"
    { "Accept" => "application/json",
      "Content-Type" => "application/json",
      "Authorization" => enc_credentials }
  end
end
